### ISSUE TITLE
mopicli not working

### ISSUE THREAD

**Issue by csanyipal** [hamishcunningham/pi-tronics#103]
Hi,
on my RPi model B+ I have a Mopi attached and the official Raspberry Pi Touch Screen.
The operating system is Raspbian Jessie with Pixel.
I am not used batteries to supply my RPi so far.
I just want to start after simbamond installation the mopi with the command:
sudo mopi
but get the message:
/usr/sbin/mopi: /usr/sbin/mopicli not working: installation problem? (mopicli, I2C bus input/output error on read word. Check bus? Check connection?)

But, when I start it with -d option, like
sudo mopi -d
then I get the application interface where I can set up Mopi. Why?

I get not any batteries with MoPi, but only two connectors for battery of 9V.
So I guess I can supply my RPi B+ and the official RPi Touch Screen with two batteries of 9V??

--
Best, from Paul

**Comment by hamishcunningham** [comment]
If the actual MoPi circuit board isn't powered up, then the software on the Pi (inc. simbamond and mopi and mopicli) can't talk to it. That's why it is giving you the error message about the I2C bus (which is what it uses to talk to the board with). The solution should be to connect batteries (or some other power supply) to the MoPi board.

9V batteries will work, but the Pi plus touch screen will use a fair amount of current. I assume you're talking about PP3 style connectors -- these will also work with containers like these: http://www.maplin.co.uk/p/10-aa-battery-box-rk45y which will supply A LOT more mAh than PP3... So if you want good battery life then 16 or 20 AAs in two boxes would work well; if you need even longer then consider 12V lead acid...

Cheers

Hamish
