### ISSUE TITLE
Raspberry Pi2 shuts down after 2 minutes because of mopi

### ISSUE THREAD

**Issue by JamesBont0078** [hamishcunningham/pi-tronics#64]
Hello there! 
I've got a problem. whenI start the Raspberry i can use it. But after a while it suddenly shuts down! I'm really confused and I hope for help.
Details:
I use a Mopi, which is connected to one LiPo battery(18Ah, 7.4 V)
When its shutted down, the mopi is still on and the Raspberry Pi has a red light, which is not blinking.
Thanks for your help!

**Comment by hamishcunningham** [comment]
hi

This sounds like either:

- you haven't configured the Simbamon daemon for your battery
- your battery is dropping voltage to below the operating floor under load

Although your battery has a big capacity, it is common for voltage drop when loaded, and 7.4V is close to MoPi's operating floor of 6.2V. So: make sure that you're correctly configured -- see https://pi.gate.ac.uk/pages/mopi.html#section-2.3. -- so that Simbamon considers anything >= 6.2V as acceptable, and if the problem persists then try adding another battery in series?

HTH, Hamish
