### ISSUE TITLE
Rainbow Square

### ISSUE THREAD

**Issue by marty-sullivan** [hamishcunningham/pi-tronics#74]
Hi, I have [this battery](http://www.amazon.com/gp/product/B011BGPUSI?psc=1&redirect=true&ref_=oh_aui_detailpage_o02_s00) and it seems to power the MoPi OK at whatever voltage I set the DC output. The MoPi status also reports the correct input voltage from the battery. However, I regularly get the dreaded "Rainbow Square" from my Pi 2 whenever it is running, signifying under voltage from the MoPi. I don't have any usb devices plugged in, just HDMI display. Is there anything I should check in the config or otherwise?

**Comment by hamishcunningham** [comment]
hi Marty,

The battery *should* be ok; I'd recommend 12V if you're not using a second
supply.

It is possible that your Pi is unusually fussy about the voltage -- MoPi's
output is a fraction under 5V in order to
allow directly connected supplies to overpower it. This doesn't create a
problem in our experience.

Does the rig actually work normally?

HTH, Best

Hamish

On 9 February 2016 at 02:32, Marty Sullivan <notifications@github.com>
wrote:

> Hi, I have this battery
> <http://www.amazon.com/gp/product/B011BGPUSI?psc=1&redirect=true&ref_=oh_aui_detailpage_o02_s00>
> and it seems to power the MoPi OK at whatever voltage I set the DC output.
> The MoPi status also reports the correct input voltage from the battery.
> However, I consistently get the dreaded "Rainbow Square" from my Pi 2
> whenever it is running, signifying under voltage from the MoPi. I don't
> have any usb devices plugged in, just HDMI display. Is there anything I
> should check in the config or otherwise?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/74>.
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455
hamish@gate.ac.uk                 https://twitter.com/@HCunningham
https://hamish.gate.ac.uk       *http://aquaponicslab.org/
<http://aquaponicslab.org/>*
https://gate.ac.uk                  https://pi.gate.ac.uk
http://www.dcs.shef.ac.uk/cgi-bin/makeperson?H.Cunningham

**Comment by marty-sullivan** [comment]
Thanks for the info. Yes, the Pi seems to run normally. I can run things fine with the ARM at 400%, no voltage warning. It consistently warns me any time I do something that suddenly draws more power, but when running at full CPU for a length of time I get no warning.
