### ISSUE TITLE
Low board voltage. RPi3 + MoPi + 12v LiFePo4 battery

### ISSUE THREAD

**Issue by Pidgeon45** [hamishcunningham/pi-tronics#82]
Hi,
I'm having issue with an RPi3 showing a low voltage warning (rainbow box, top right of screen) when powered by a MoPi and 12v LiFePo4 battery. The battery is fully charged and MoPi reports a 12.78v supply. I measure ~4.75v across test pads PP3 and PP7 when using this setup, which accounts for the low voltage warning. When the MoPi is removed and the RPi is powered via micro-USB, there is no low voltage warning and the voltage across test pads is ~5.05v. Can I assume the MoPi (#2177) to be faulty?

**Comment by guruthree** [comment]
The MoPi intentionally supplies slightly less than 5v so that if a micro USB power source is attached, it is the preferred power source, saving the batteries. Your MoPi is functioning correctly, just unfortunately the low-voltage warning of the RPi3 was never anticipated in this scenario. This is something that will be addressed in the next version of the MoPi hardware.
