### ISSUE TITLE
Changing firmware on Mopi

### ISSUE THREAD

**Issue by jeberhardt** [hamishcunningham/pi-tronics#92]
Hello;

I am wondering if it's possible to change the firmware on the Mopi itself.  What I'd like to do is change it so that the Mopi will drain battery #1 before it starts using battery #2. I hope this is a change that I can make.

Thanks.

**Comment by jeberhardt** [comment]
bump

**Comment by hamishcunningham** [comment]
Sorry -- it isn't possible to do this (reflash) at present :-(

Incidentally I could be wrong but I don't think it would be a firmware-level change, because IIRR the drain is always from the higher voltage source at a hardware level.

Lubo is near to the final prototype stage for a new MoPi, and I'll copy him on this in case he thinks he can do it in the new one...

Cheers

h
